<!-- CSS -->
<link href="bower/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="bower/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="bower/angular-motion/dist/angular-motion.min.css" rel="stylesheet" type="text/css">
<link href="bower/bootstrap-additions/dist/bootstrap-additions.min.css" rel="stylesheet" type="text/css">
<link href="css/basic.css" rel="stylesheet" type="text/css">

<!-- UNDERSCORE -->
<script type="text/javascript" src="bower/underscore/underscore.js"></script>

<!-- JQUERY -->
<script type="text/javascript" src="bower/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="bower/jquery-ui/ui/minified/jquery-ui.min.js"></script>

<!-- ANGULAR -->
<script type="text/javascript" src="bower/angular/angular.js"></script>
<script type="text/javascript" src="bower/angular-strap/dist/angular-strap.js"></script>
<script type="text/javascript" src="bower/angular-strap/dist/angular-strap.tpl.min.js"></script>
<script type="text/javascript" src="bower/angular-promise-tracker/promise-tracker.js"></script>
<script type="text/javascript" src="bower/angular-route/angular-route.min.js"></script>
<script type="text/javascript" src="bower/angular-animate/angular-animate.min.js"></script>
<script type="text/javascript" src="bower/angular-sanitize/angular-sanitize.min.js"></script>
<script type="text/javascript" src="bower/angular-ui-sortable/sortable.js"></script>
<script type="text/javascript" src="bower/angular-ui-bootstrap/src/pagination/pagination.js"></script>
<script type="text/javascript" src="bower/angular-growl/build/angular-growl.min.js"></script>

<!-- APPLICATION LAUNCH -->
<script type="text/javascript" src="js/application.js"></script>